name: helloworld-ci
run-name: helloworld-ci for building and packaging helloworld app
on: 
  push:
    tags: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repo
      - uses: actions/setup-go@v5
        name: Build with go
        with:
          go-version: '1.22.0'
      - run: echo 'pipeline is starting'
      - run: go test ./...
      - run: go build -o main
      - uses: docker/setup-buildx-action@v3
        driver: docker-container
        with:
          config-inline: |
            [registry."registry:5000"]
              http = true
              insecure = true
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "registry:5000/helloworld:${{ gitea.ref_name }}"